project/Common.scala
project/plugins.sbt

You will run into https://github.com/sbt/sbt-pgp/issues/67 if you have ~/.sbt/0.13/plugins/gpg.sbt loaded with 1.0.0 and a project configured with 0.8.3.  The simplest solution here is to upgrade to 1.0.0.

Upgrade to sbt-pgp 1.0.0

---

src/main/scala/com/typesafe/scalalogging/Logger.scala
src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala

Currently the logger could not be serializable which forces extending classes to override the logger to declare it as transient, which leads to null loggers on deserialization.  Since the slf4j logger is serializable we can make our logger serializable as well.
ref #26 #44

Made Logger serializable

---

README.md

For people who never used SLF4J and Logback, or only programmed in Scala, this can be very useful.

Update README: add Logback to sbt.build

---

.travis.yml
project/Common.scala
project/Dependencies.scala
project/plugins.sbt

Scala 2.12

---

README.md
src/main/scala/com/typesafe/scalalogging/LoggerMacro.scala
src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerWithMarkerSpec.scala

New feature that allows the users to use Scala's string interpolation that is automatically translated to SFL4J string interpolation so that tools like Sentry work correctly.
Unfortunately this approach has its limitations which are described in README.

String Interpolation

---

src/main/scala/com/typesafe/scalalogging/LoggerMacro.scala
src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala

The interpolation destructuring added in 3.6.0 attempts to convert interpolated messages to slf4j message formatting calls. These have signature `(String, Object*)Unit`, and as such any interpolations involving value types result in compilation errors. The simplest fix I came up with for this is to invoke `toString` on such interpolations, as they cannot be null.
The implementation also doesn't escape `{}` appearing in string parts, and doesn't account for Scala's wonky escape handling for interpolators.

Fix compile errors for interpolated AnyVals

---

src/main/scala/com/typesafe/scalalogging/LoggerMacro.scala
src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala

Fixes #38
When using standard sl4j interpolator and `Any` args [it fails](https://scastie.scala-lang.org/3GLKMBwvQbq1N54BfkjlBA):
```
logger.debug("test {} and {} and {}", 1, 2, 3)
[error] overloaded method value debug with alternatives:
(x$1: org.slf4j.Marker,x$2: String,x$3: Object*)Unit 
(x$1: org.slf4j.Marker,x$2: String,x$3: Any,x$4: Any)Unit 
(x$1: String,x$2: Object*)Unit
cannot be applied to (String, Int, Int, Int)
```
#87 brings optional mapping to AnyRef  but only for standard scala string interpolation. This PR moves formatting args to be applied before each log call but not only for scala string interpolation

Make logger to consume args of type `Any` with slf4 interpolator.

---

.travis.yml

https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879
> My guess is that we can no longer support oraclejdk7 on our recent build images due to Oracle's withdrawal. http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html
https://travis-ci.org/typesafehub/scala-logging/jobs/319727211
```
$ export JDK=oraclejdk7
Disabling Gradle daemon
0.00s$ mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
$ export PATH=$JAVA_HOME/bin:$PATH
$ export JVM_OPTS=@/etc/sbt/jvmopts
$ export SBT_OPTS=@/etc/sbt/sbtopts
$ java -Xmx32m -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_151
```

travis-ci no longer support oraclejdk7

---

project/Dependencies.scala

Some dependency and security checkers complain about scala 2.11.11 and scala 2.12.<4 artifacts due to the compiler security issue. Would be nice if we could get a scala-logging 3.7.3 release out soon.

Update to scala 2.11.12

---

README.md
src/main/scala/com/typesafe/scalalogging/Logger.scala
src/main/scala/com/typesafe/scalalogging/LoggerTakingImplicit.scala
src/main/scala/com/typesafe/scalalogging/LoggerTakingImplicitMacro.scala
src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerTakingImplicitSpec.scala

Including request contextual data in the logs (e.g. `CorrelationId`, `UserId`, etc.) is a common scenario, however currently there is no good way to do it.
With Java common approach is to use MDC, however I think that in Scala it's a bad idea for two reasons:
-  in case of async computations custom execution context is needed, but more importantly
- correlationId value is not present in the function signature and then it's taken out of thin air which in Scala should be a serious red flag
Here is relevant part of the code that expresses idea in this pull request:
```scala
trait CanLog[A] {
def logMessage(originalMsg: String, a: A): String
def afterLog(a: A): Unit = ()
}
class LoggerTakingImplicit[A] (val underlying: Underlying)(implicit val canLogEv: CanLog[A]) { 
def error(message: …
```

Added Logger that takes an implicit parameter (e.g. CorrelationId)

---

src/main/scala/com/typesafe/scalalogging/Logging.scala

See also http://fdahms.com/2015/10/14/scala-and-the-transient-lazy-val-pattern/

`lazy val logger` field should be transient

---

src/main/scala/com/typesafe/scalalogging/LoggerMacro.scala
src/main/scala/com/typesafe/scalalogging/LoggerTakingImplicitMacro.scala
src/test/scala/com/typesafe/scalalogging/LoggerWithMarkerSpec.scala

- Use `marker` inside macros in *Enabled methods
- fixes https://github.com/lightbend/scala-logging/issues/139

Use marker inside macros in *Enabled methods

---

.travis.yml
build.sbt
project/Dependencies.scala
src/main/scala/com/typesafe/scalalogging/LoggerMacro.scala
src/main/scala/com/typesafe/scalalogging/package.scala
src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerTakingImplicitSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerWithMarkerSpec.scala

Upgrade to 2.13.0-RC2 (note: there's a temporary hack to use RC1 artifacts for mockit-scala).
Also clarify (hopefully correctly) use of varargs (not really related to the 2.13 upgrade, but somehow it broke). /cc @szeiger, maybe you have an idea why? (something to do with the switch to immutable seq for varargs?)

Upgrade 2.13

---

.travis.yml
project/Dependencies.scala

details:
- Scala:    2.13.0-RC2 -->> 2.13.0-RC3
- mockito-scala: 1.4.6 -->> 1.5.0 https://github.com/mockito/mockito-scala/blob/v1.5.0/docs/release-notes.md
- scalatest: 3.0.8-RC4 -->> 3.0.8-RC5

Version upgrade: Scala 2.13.0-RC3

---

build.sbt
src/main/scala/com/typesafe/scalalogging/Logger.scala
src/main/scala/com/typesafe/scalalogging/LoggerMacro.scala
src/main/scala/com/typesafe/scalalogging/LoggerTakingImplicit.scala
src/main/scala/com/typesafe/scalalogging/LoggerTakingImplicitMacro.scala

This PR enables the `-Ywarn-unused` compiler flag and performs some cleanup with the additional warnings. There is 1 warning that I am unable to resolve, and I'll open an issue about this.

Enable -Ywarn-unused + code cleanup

---

src/main/scala/com/typesafe/scalalogging/LoggerMacro.scala
src/test/scala/com/typesafe/scalalogging/LoggerWithTaggedArgsSpec.scala

Fixes https://github.com/lightbend/scala-logging/issues/111

Fix for shapeless `@@` types passed on as args

---

.gitignore
.travis.yml
project/Dependencies.scala
src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerTakingImplicitSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerWithMarkerSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerWithTaggedArgsSpec.scala

Setup jdk taken from travis docs:
https://docs.travis-ci.com/user/languages/java/#using-java-10-and-late
Similar to(fix openjdk 11): https://github.com/lightbend/scala-logging/pull/228
Also contains(mockito-scala 1.5.18): https://github.com/lightbend/scala-logging/pull/188
Also contains(scalatest 3.2.0): https://github.com/lightbend/scala-logging/pull/222
Also contains(scalatest 3.2.1): https://github.com/lightbend/scala-logging/pull/226
Bumping scala 2.13.1 -> 2.13.3 causes jvm panic for oraclejdk11 that's why it is not included here.
2.13.3 works locally okay for me with oraclejdk11, maybe travis uses older version with some kind of bug?
Anyway just worth to mention it somewhere.
Anyone could take a look at this PR? It is mainly maintenance work and maybe groundwork for PR dotty …

Travis fix for jdk11

---

project/Dependencies.scala
src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerTakingImplicitSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerWithMarkerSpec.scala
src/test/scala/com/typesafe/scalalogging/LoggerWithTaggedArgsSpec.scala

Inspired by the comment on #172 this PR uses the ScalaTest integration of mockito-scala so all mocks are strict by default.
An easy way to verify this would be to re-write the first test on `LoggerSpec` as (notice the extra direct call to `underlying.info`
```scala
"call the underlying logger's error method if the error level is enabled" in {
val f = fixture(_.isErrorEnabled, isEnabled = true)
import f._
logger.error(msg)
underlying.info("called by accident")
verify(underlying).error(msg)
}
```
Executing such test would fail as
```
Unexpected invocations found
The following invocations are unexpected (click to navigate to relevant line of code):
1. logger.info("called by accident"); -> at com.typesafe.scalalogging.LoggerSpec.$anonfun$new$2(LoggerSpec.scala:26)
Please make sure you aren't …
```

Use mockito-scala-scalatest to enable strict mocks on all tests.

---

.travis.yml
README.md
build.sbt
project/Dependencies.scala
project/plugins.sbt
version.sbt

includes adopting sbt-dynver (to set `version`) and sbt-travisci (to set `scalaVersion` and `crossScalaVersions`)
fixes #254

replace sbt-release with sbt-ci-release

---

.travis.yml
project/Dependencies.scala

Also updates Scalatest to 3.2.9, as 3.2.8 doesn't have a 3.0.0 build.

Update to Scala 3.0.0

---

.travis.yml

(secondary purpose of this PR to make sure Travis-CI is triggering and running again; we needed to renew our Lightbend plan)

bump Scala versions (2.12.14, 2.13.6)

---

README.md

Version 3.9.3 is only published for `3.0.0-RC1`
Whereas 3.9.4 is published for `3` which better matches the prerequisites in  the readme.
https://mvnrepository.com/artifact/com.typesafe.scala-logging/scala-logging

Use 3.9.4 in readme for Scala 3

---

README.md

Just with all the logging CVEs going about and even logback having some - just thought it would be good to update the logback version in the readme.

doc: latest logback version

---

src/main/scala-2/com/typesafe/scalalogging/LoggerMacro.scala
src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala

When passing an interpolated string with a `Throwable`, the Scala 2 macro incorrectly calls the non-format overload:
```java
public void error(String msg, Throwable t);
```
Coerce all arguments to `AnyRef` so that the format overload is used:
```java
public void error(String format, Object arg);
```
Fixes #216
Fixes #95

Fix macro when interpolated argument is `Throwable`

---

src/main/scala-2/com/typesafe/scalalogging/LoggerTakingImplicitImpl.scala
src/main/scala-2/com/typesafe/scalalogging/LoggerTakingImplicitMacro.scala

Added the missing when***Enabled() methods in LoggerTakingImplicitImpl

---

src/main/scala-2/com/typesafe/scalalogging/LoggerTakingImplicitImpl.scala
src/main/scala-2/com/typesafe/scalalogging/LoggerTakingImplicitMacro.scala
src/main/scala-3/com/typesafe/scalalogging/LoggerTakingImplicitImpl.scala
src/main/scala-3/com/typesafe/scalalogging/LoggerTakingImplicitMacro.scala

References #292 
I have noticed that these `when***Enabled()` methods were also missing from [LoggerTakingImplicitImpl](https://github.com/lightbend/scala-logging/blob/main/src/main/scala-3/com/typesafe/scalalogging/LoggerTakingImplicitImpl.scala) under [scala-3/com/typesafe/scalalogging](https://github.com/lightbend/scala-logging/tree/main/src/main/scala-3/com/typesafe/scalalogging) package. So i have added them there as well.

Scala-3: Added the missing when***Enabled() methods in LoggerTakingImplicitImpl under scala-3 package

---

README.md

References #147 
As we have introduced `AnyLogging` in `com.typesafe.scalalogging`, we also need its description in **README**. So I've added that.

Added description for AnyLogging in README

---

src/test/scala/com/typesafe/scalalogging/LoggerTakingImplicitSpec.scala

Added a test case for getContext method in LoggerTakingImplicitSpec

---

README.md

Updated docs with getContext

---

src/test/scala/com/typesafe/scalalogging/LoggerWithMarkerSpec.scala

Added missing type annotations in LoggerWithMarkerSpec

---

src/test/scala/com/typesafe/scalalogging/LoggerSpec.scala

Removed type annotations warnings in LoggerSpec

---

.github/workflows/ci.yml

this recently became possible in recent sbt versions (1.7.x, I think)

adjust CI config to avoid repeating Scala version numbers
